In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.ndim

1

In [6]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.ndim

2

In [8]:
arr_2d.size

8

In [9]:
arr_2d.shape

(2, 4)

In [10]:
arr_2d.dtype

dtype('int32')

In [11]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])