In [1]:
import numpy as np

In [6]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
mx_1s = np.ones(5)

In [8]:
mx_1s.dtype

dtype('float64')

In [10]:
mx_1s = np.ones((3,5))

In [11]:
mx_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
mx_1s = np.ones((3,5),dtype=int)
mx_1s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
mx_0s = np.zeros((3,5))
mx_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
mx_0s = np.zeros((3,5),dtype=bool)
mx_0s

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [15]:
mx_0s = np.zeros((3,5),dtype=str)
mx_0s

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [16]:
mx_empty = np.empty((3,5))
mx_empty

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])