# Random sampling with numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.74076457])

In [3]:
np.random.random((3,3))

array([[0.30405628, 0.62865147, 0.16963653],
       [0.68603766, 0.3514215 , 0.09683582],
       [0.37314665, 0.83661128, 0.34932728]])

In [6]:
np.random.randint(1,4,(3,3))

array([[2, 1, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [7]:
np.random.randint(1,4,(2,3,3))

array([[[1, 1, 2],
        [3, 1, 2],
        [2, 1, 2]],

       [[1, 3, 2],
        [3, 3, 3],
        [3, 1, 3]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4,(2,3,3))

array([[[2, 2, 1],
        [1, 2, 1],
        [2, 2, 1]],

       [[2, 2, 3],
        [1, 2, 1],
        [3, 1, 3]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,3,3))

array([[[2, 2, 1],
        [1, 2, 1],
        [2, 2, 1]],

       [[2, 2, 3],
        [1, 2, 1],
        [3, 1, 3]]])

In [11]:
2**32-1

4294967295

In [12]:
np.random.rand(3)

array([0.68535982, 0.95339335, 0.00394827])

In [13]:
np.random.rand(3,3)

array([[0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005]])

In [14]:
np.random.randn(3,3)

array([[ 1.484537  , -1.07980489, -1.97772828],
       [-1.7433723 ,  0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221,  0.09914922]])

In [15]:
x = [1,2,3,4]
np.random.choice(x)

1

In [16]:
np.random.choice(x)

3

In [17]:
for i in range(20):
    print(np.random.choice(x))

1
2
4
3
1
3
4
1
4
2
3
4
4
1
2
1
3
1
1
1


In [18]:
x

[1, 2, 3, 4]

In [19]:
np.random.permutation(x)

array([3, 4, 1, 2])